### ISSUE TITLE
Is this package secure?

### ISSUE THREAD

**Issue by minfawang** [qnub/emojione-react#1]
![screen shot 2015-11-11 at 2 41 46 pm](https://cloud.githubusercontent.com/assets/8814693/11105227/67273630-8882-11e5-9758-e4fd85b9fbab.png)
I just did some experiments and tried to input

```
hello :grin: world <script>console.log("hello world");</script>
```

Then I inspected the element and found this in the chrome developer tool. Although I didn't really see the `hello world` message printed to the console, but it looks indeed scary to me.

I wonder if this kind of security issue actually covered in the parsing string function or do I have to take care of it myself before passing the string to this function?

**Comment by qnub** [comment]
Not sure about details, i've just make package for meteor. But i think you should remove unnecessary tags from string before pass it to function or use only shortcodes instead full string. This is original function: https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L152

**Comment by minfawang** [comment]
Ok I found out that they actually have defined the [HTML escaping function](https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L392-L403) themselves, but didn't use it inside the function of `toImage`.

I recommend you to include this part in your code. So people don't need to remember to include the escape function every time using this component. So you can just change [here](https://github.com/qnub/emojione-react/blob/master/components/emojione.jsx#L11) to:

```
content: emojione.toImage( emojione.escapeHTML(text) )
```

**Comment by qnub** [comment]
Maybe i'll add additional property to allow unescaped HTML, because in my project i need to display some raw HTML with emojis. Thanks for your suggestions :+1:

**Comment by qnub** [comment]
By default it'll be escaped, of course…

**Comment by minfawang** [comment]
Oh sounds like a great option! Thanks for creating this package!
